### ISSUE TITLE
Question: PieChart Animation

### ISSUE THREAD

**Issue by cubecnelson** [JesperLekland/react-native-svg-charts#333]
I tried to set the animate={true}, animateDuration={3000} to a PieChart, and it seems there are no animations on the PieChart when i was trying the endAngle and the data.

**Comment by headfire94** [comment]
I noticed that library imports `Path` from `react-native-svg` https://github.com/JesperLekland/react-native-svg-charts/blob/dev/src/pie-chart.js#L5 instead of `animated-path` from https://github.com/JesperLekland/react-native-svg-charts/blob/dev/src/animated-path.js
Looks like it's mistake, otherwise why pass `animate` prop to `path` ? https://github.com/JesperLekland/react-native-svg-charts/blob/dev/src/pie-chart.js#L153

**Comment by JesperLekland** [comment]
The PieChart animation turned out pretty poor so I decided to disable it in order to now have a bunch of issues on account of it morphing like crazy.

**Comment by obiwankenoobi** [comment]
@JesperLekland Any planing to turn in back in the future? (:

**Comment by SyedShahbazHussain** [comment]
> The PieChart animation turned out pretty poor so I decided to disable it in order to now have a bunch of issues on account of it morphing like crazy.

Waiting for PieChart Animation

**Comment by JesperLekland** [comment]
> > The PieChart animation turned out pretty poor so I decided to disable it in order to now have a bunch of issues on account of it morphing like crazy.
> 
> Waiting for PieChart Animation

You are more than welcome to supply a PR with said feature 👍

**Comment by tolik85** [comment]
@cubecnelson Guys, any updates on this? This is quite a frequent feature request

**Comment by Rohitsaxena** [comment]
Using Animated.View from react-native-reanimated fixed it for me.
I think this could help for you guys.

**Comment by IronTony** [comment]
@Rohitsaxena can you provide a small example please?
Thank you

**Comment by jscul** [comment]
@Rohitsaxena can you elaborate?
