### ISSUE TITLE
Is there a way to limit the number of points displayed on the X-axis?

### ISSUE THREAD

**Issue by kchangch** [JesperLekland/react-native-svg-charts#479]
Hi, I would like to know if there is a way to limit the number of points i want to display on the X-axis label. Please let me know if there is any possible way.

Thanks.

**Comment by ajacquierbret** [comment]
Hi @kchangch  ! Of course, use the 'numberOfTicks' prop.

**Comment by kchangch** [comment]
@ajacquierbret thanks for the response. I have done that, currently i have numberOfTicks = {5} but the graph is still showing me more labels on the X-Axis than what I specified. Look at the attachment.

<img width="352" alt="Screen Shot 2020-07-02 at 1 55 45 PM" src="https://user-images.githubusercontent.com/43304067/86408472-ea7ffb80-bc6b-11ea-8f67-58d4ddf5b18f.png">

**Comment by ajacquierbret** [comment]
You're welcome @kchangch ! I will quote a comment I wrote about a related issue :

> The 'numberOfTicks' prop is giving you the ability to provide a kind of 'parameter value', but it will almost never render the same number of axis values [...]. The underlying process is handled by d3 and is not just a dumb calculation of the value you provide to this prop.

In other words, showing the exact same number on your axis as the one you provided to the 'numberOfTicks' will almost never happen. Check out this issue and you will maybe find my workaround useful : https://github.com/JesperLekland/react-native-svg-charts/issues/484#issuecomment-652863393

You could pass the value of the 'formatLabel' prop to a function that would return the desired number of labels. In my case, selective and exclusive iteration has been done by using the modulus operator, as explained in the issue I just mentioned.

If it still doesn't solve your issue, try to play with differents scales provided by d3-scale, `scale={scale.scaleTime}` by exemple. I hope it helps !

**Comment by kchangch** [comment]
@ajacquierbret thanks for the help and quick response! Really appreciate it. I have one more question, sometimes my labels seem to render on screen even though they are cut off. Is there a way to code it in a way that if it doesn't render fully, then don't render? Like this image

![Simulator Screen Shot - iPhone 11 Pro - 2020-07-02 at 16 00 13](https://user-images.githubusercontent.com/43304067/86415884-36876c00-bc7d-11ea-98d6-1497f351189c.png)

As you can see, the label on the left corner is no longer fully render. Is there a way to avoid that to happen?

**Comment by ajacquierbret** [comment]
You could set a different value for the `contentInset` prop, in this case you need to increase `left` and `right` values.

e.g. `contentInset={{ left: 20, right: 20 }}`

**Be shure to set the same values on the chart's `contentInset` prop in order to make sure that the xAxis will still be correctly aligned with its corresponding chart.**

Eventually, you could replace your first label by some empty string or transparent color using the `formatLabel` prop, so that the first index is still there and calculated by d3-scale, but not shown. But it sound more like a hack than a real fix. The "official" way is to set a correct `contentInset` value.

Finaly, you could calculate label lengths and compare it to xAxis total length, but honestly I don't think it's the right thing to do, and anyway I wouldn't know how to do it. Maybe some CSS overflow settings if the previous solution doesn't work ? (Be careful with iOS/Android handling of overflow)

Feel free to tell me if it doesn't work (or if it works) !

**Comment by kchangch** [comment]
Sounds good, I will try it now and let you now. Thank you!

**Comment by ajacquierbret** [comment]
Be sure to close this issue or to ask do to so if your problem was solved ! :)

**Comment by kchangch** [comment]
Thanks for the help! I figure out how to get this working. If there is any question, is it possible to contact you again?

**Comment by ajacquierbret** [comment]
Hi @kchangch ! You're welcome ! Glad it worked, and of course if you need me to help you again, I'll be happy to do so !
