### ISSUE TITLE
Not able to create two Y axes with the same scale and number of ticks

### ISSUE THREAD

**Issue by ronkot** [JesperLekland/react-native-svg-charts#482]
I'm creating a stacked chart where bars represent electricity consumption and lines represent outside temperature:

![image](https://user-images.githubusercontent.com/8327634/85319401-1eb82700-b4ca-11ea-91fb-c0fffa9e1613.png)

I'm trying to achieve a chart where the temperature labels would align with the grid lines rendered by the consumption data as they do on the Y axis on the left. But as it can be seen from the pic above, both the number of ticks and their position is different from the ones in the consumption axis. This is something that seems like a bug, as I'm using the same value (5) for the `numberOfTicks` prop. But is this just a _feature_ that's caused by the underlying d3 library? Please help me to understand how the Y axis scaling works 🙏 😄 

Below a simplified code:

```javascript
<View
  style={{
    height: 300,
    flexDirection: 'row',
  }}>
  <YAxis
    data={consumptionData}
    style={{ marginBottom: 20 }}
    numberOfTicks={5}
  />
  <View style={{ flex: 1 }}>
    <BarChart
      style={{ flex: 1 }}
      numberOfTicks={5}
      data={consumptionData}>
      <Grid />
    </BarChart>
    <LineChart
      style={{
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 20,
      }}
      data={temperatureData}
      numberOfTicks={5}
    />
    <XAxis style={{ height: 20 }} data={consumptionData} />
  </View>
  <YAxis
    data={temperatureData}
    style={{ marginBottom: 20 }}
    numberOfTicks={5}
  />
</View>
```

**Comment by ajacquierbret** [comment]
Hey @ronkot ! I'm using exactly the same units, energy consumption and temperatures on double Y axes, so we're on the same boat ! :)

Here's my config for double Y axis chart :

```javascript
export const AppDoubleYAxisLineChart = () => {
  return (
    <AppView
      style={{
        width: containerWidth,
        height: totalHeight,
        marginVertical: marginVertical,
      }}
    >
      <AppView style={{ flexDirection: 'row', alignContent: 'space-between' }}>
        <AppView>
          <YAxis
            style={{ height: totalHeight }}
            data={firstLineData}
            contentInset={contentInset}
            svg={leftAxisSvg}
            formatLabel={formatLeftYLabel}
            numberOfTicks={leftYTicks}
          />
        </AppView>
        <AppView
          style={{
            flex: 1,
            height: totalHeight,
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          <AreaChart
            style={{
              height: totalHeight,
              width: '90%',
              bottom: 0,
              position: 'absolute',
              margin: 'auto',
            }}
            data={firstLineData}
            contentInset={contentInset}
            curve={shape.curveLinear}
            svg={firstLineSvg}
            numberOfTicks={leftYTicks}
            xScale={scale.scaleTime}
          >
            <Line color={firstLineColor} />
            {withGradient ? <Gradient color={firstLineGradientColor} y2={firstLineGradientPercentage} fromOpacity={firstLineGradientOpacity} /> : null}
          </AreaChart>
          <AreaChart
            style={{
              height: totalHeight,
              width: '90%',
              bottom: 0,
              position: 'absolute',
              margin: 'auto',
            }}
            data={secondLineData}
            contentInset={contentInset}
            curve={shape.curveBasis}
            svg={secondLineSvg}
            numberOfTicks={rightYTicks}
            xScale={scale.scaleTime}
          >
            <Line color={secondLineColor} />
            {withGradient ? <Gradient color={secondLineGradientColor} y2={secondLineGradientPercentage} fromOpacity={secondLineGradientOpacity} /> : null}
          </AreaChart>
          <XAxis
            style={{
              width: '90%',
              position: 'absolute',
              bottom: -30,
            }}
            contentInset={{ left: 20, right: 20 }}
            data={xAxisData}
            svg={xAxisSvg}
            formatLabel={formatXLabel}
            xAccessor={xAccessor}
            scale={scale.scaleTime}
          />
        </AppView>
        <AppView>
          <YAxis
            style={{ height: totalHeight }}
            data={secondLineData}
            contentInset={contentInset}
            svg={rightAxisSvg}
            formatLabel={formatRightYLabel}
            numberOfTicks={rightYTicks}
          />
        </AppView>
      </AppView>
    </AppView>
  );
};
```

Unfortunately I changed my way of handling it, and now use two separated charts instead of two overlapping charts.

<img width="375" alt="Capture d’écran 2020-07-02 à 09 58 26" src="https://user-images.githubusercontent.com/45269819/86332365-b8aa6d00-bc4a-11ea-81ec-2619d760cf76.png">

The only way to get the exact number of values on both axes is, I guess, to tweak a bit the library.

The 'numberOfTicks' prop is giving you the ability to provide a kind of 'parameter value', but it will almost never render the same number of axis values if your datasets are different. The underlying process is handled by d3 and is not just a dumb calculation of the value you provide to this prop.

I made some researches and I found that the only way to achieve what you're trying to do is to provide an interval more than a fixed number of ticks, but it doesn't seem to be implemented yet, and will certainly not be available for Y axes. Anyway, try to play a bit with the children 'ticks' prop, maybe it can solve your issue.

An interesting post about this issue : http://www.d3noob.org/2016/08/changing-number-of-ticks-on-axis-in.html

I opened a feature request a few minutes ago about time intervals : #484

**Comment by ajacquierbret** [comment]
Ok, I may found a workaround for your issue, try to play with your label indexes instead of using the 'numberOfTicks' prop, because your goal is to have a consistent number of labels on your Y axes.

Related issue : https://github.com/JesperLekland/react-native-svg-charts/issues/484#issuecomment-652863393

**Comment by JesperLekland** [comment]
Thank you Adrien for doing your research and helping out in answering related issues. It's people like you that make open source fun and rewarding! 🥇

**Comment by ajacquierbret** [comment]
> Thank you Adrien for doing your research and helping out in answering related issues. It's people like you that make open source fun and rewarding! 🥇

Ahah you're welcome, it's always nice to share solutions with others ! :)

**Comment by ronkot** [comment]
Thanks @ajacquierbret for insights and tips and @JesperLekland for your great work with this library. And what a coincidence that we're building same kind of charts 😄 

I'll try to play with the parameters and also try the axis label formatting trick. Maybe I'll also have to study a bit d3 😬 😅

**Comment by ajacquierbret** [comment]
Remember to close this issue or to ask do to so if your problem was solved ! :)

**Comment by ronkot** [comment]
Back from the holidays.. I'll close this issue for now and try these tips when I'll have again time to investigate this issue. Once again, thanks for help and this great library 💎
