### ISSUE TITLE
Question about ContentInset for XAxis

### ISSUE THREAD

**Issue by msevestre** [JesperLekland/react-native-svg-charts#91]
I am a bit puzzled by the documentation regarding the XAxis props.
Especially this sentence

>If the chart has property contentInset set it's very important that the XAxis has the same horizontal contentInset.

I do not understand why setting `contentInset={{ top: 10, bottom: 10 }}` on the chart would lead to the XAxis needing to have `contentInset={{ left: 10, right: 10 }}`. I understand that this is required for the Y Axis but the X-Axis should not be affected by vertical padding.  I am clearly missing something obvious and would appreciate a clarification.

Thanks for your help,
Michael

**Comment by JesperLekland** [comment]
You are correct in your assumption. What the readme states is that if the chart has contentInset (non zero horizontal values) the XAxis needs the same horizontal inset.

Does that answer your question?

**Comment by msevestre** [comment]
@JesperLekland Thanks for the quick feedback.

Let's turn the question around then. If the XAxis has some horizontal contentInset as in the example, should not the chart also has them as well? In the ReadMe example, my assumption would be that the X-axis would not be aligned with the chart as expected. 

Also the XAxis.svg has a property originY that is being set to various values in your example. Could you explain what this property does? 

The react-native-svg doc says `Transform originY coordinates for the current object`... but I am not sure that that means :)

Thanks again

**Comment by JesperLekland** [comment]
Fair enough. In the example the xAxis has both a negative horizontalMargin and a positive contentInset of the same value. This is to allow the xAxis to be bigger than the chart but still only calculate its coordinates in the same space as the chart. If those props would be omitted the labels would be clipped (at least on Android). I hope that answered your question.

originY is a bit tricky, I would recommend reading up on the regular css svg property of "originY". Basically it has to do with that the origin of a rotation is. If not set all labels would rotate around the canvas's [0,0] coordinate instead of their own origin

**Comment by msevestre** [comment]
> I hope that answered your question.

Perfect. Very clear answer. Thanks again
